version: '3.8'

services:
  mysql-docker:
    image: mysql:latest
    container_name: mysql-docker
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin

  phpmyadmin-docker:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin-docker
    depends_on:
      - mysql-docker
    environment:
      PMA_HOST: mysql-docker
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"